/** One-line SEO/AEO tips shown while an analysis + article generate. Static, no cost. */
export const SEO_TIPS: readonly string[] = [
  "Answer the query in the first sentence — engines lift direct answers into AI overviews",
  "One H1 per page; let H2s map to the questions real people ask",
  "Front-load the keyword in your title, but write the title for a human first",
  "A table beats three paragraphs when you're comparing options",
  "Internal links pass context, not just authority — link to your best related answer",
  "Write meta descriptions as a pitch, not a summary — they drive clicks, not rankings",
  "Use FAQ schema only on content that actually answers the questions it marks up",
  "Short paragraphs and clear headers help both skimmers and AI extractors",
  "Canonical tags stop duplicate content from splitting your ranking signal",
  "Page speed is a ranking factor and a conversion factor — fix both with one effort",
  "Cite your sources; AI overviews favor pages that show their work",
  "Update old posts with new data instead of always publishing new ones",
  "Alt text should describe the image, not stuff in keywords",
  "A single, specific claim per sentence is easier for engines to extract as an answer",
  "Break long guides into numbered steps — structure is a ranking signal now",
  "Match search intent first, keyword volume second",
  "Author bios with real credentials help E-E-A-T on YMYL topics",
  "Internal anchor text should describe the destination, not just say 'click here'",
  "Structured data errors quietly kill rich results — validate after every template change",
  "Mobile page speed matters more than desktop; most searches happen on phones",
  "Answer 'what', 'why', and 'how' in distinct, scannable sections",
  "Backlinks from topically relevant sites outweigh backlinks from high-DA irrelevant ones",
  "Refresh publish dates only when you've meaningfully updated the content",
  "Use descriptive URL slugs — /best-running-shoes beats /post?id=4821",
  "Avoid keyword stuffing; write for the reader and let synonyms happen naturally",
  "A clear byline and last-updated date build trust signals engines can read",
  "Break out comparison content into a table so AI can lift it as a direct answer",
  "301 redirect old URLs instead of leaving them to 404 when content moves",
  "Group related posts into a topic cluster linked from one pillar page",
  "Keep title tags under 60 characters so they don't truncate in results",
  "Use one primary keyword per page — don't make pages compete with each other",
  "Answer follow-up questions in the same article instead of forcing another click",
  "Compress images and serve modern formats to cut load time without losing quality",
  "Write for the person who has ten seconds, then reward the person who stays",
  "A definitions section near the top helps both new readers and AI summarizers",
  "Avoid thin pages — merge or expand content that can't stand on its own",
  "Use HowTo schema only for genuine step-by-step processes, not general advice",
  "Link out to authoritative sources when you cite a stat or study",
  "Crawlable pagination beats infinite scroll for indexation of list content",
  "Keep your robots.txt lean — don't accidentally block pages you want indexed",
  "Avoid duplicate meta descriptions across a category's pages",
  "Bullet lists of pros and cons are easy for engines to extract as an answer",
  "Test your schema markup with a validator before you ship it, not after",
  "Write headings as questions when the section literally answers a question",
  "Consolidate near-duplicate posts instead of letting them cannibalize rankings",
  "A fast time-to-first-byte matters more than most on-page tweaks combined",
  "Use breadcrumb schema so search results show your site hierarchy",
  "Don't bury the answer under a life story — get to the point in the first 100 words",
  "Reciprocal internal links between related guides help crawlers find deep content",
  "Keep your XML sitemap current — stale sitemaps waste crawl budget",
  "Write for one search intent per page: informational, navigational, or transactional",
  "Long-tail questions in H2s often rank faster than broad head terms",
  "Avoid interstitial pop-ups that block content on mobile — they hurt both UX and SEO",
  "Use lazy loading for below-the-fold images, not for anything above the fold",
  "A glossary page can become a magnet for definitional, answer-seeking queries",
  "Check for orphan pages — every page should be reachable via internal links",
  "Match your H1 to the query's intent, not just the keyword string",
  "Publish original data or research; it earns links that generic advice can't",
  "Keep JavaScript-rendered content crawlable — test with a raw HTML fetch",
  "Trim navigation clutter so link equity flows to your most important pages",
  "Use noindex, not robots.txt disallow, to keep low-value pages out of the index",
  "Write comparison tables with consistent columns so engines can parse them cleanly",
  "A concise summary box near the top increases your odds of an AI overview citation",
  "Avoid AI-generated filler; unique insight is what differentiates ranking content now",
  "Keep URLs stable — changing them without redirects resets accumulated authority",
  "Use descriptive link text for outbound citations, not raw URLs",
  "Server response time under 200ms keeps both users and crawlers happy",
  "Structure recipes, reviews, and events with the schema type built for them",
  "Don't hide key content behind tabs or accordions that crawlers can't expand",
  "A strong opening paragraph should work as a standalone answer if quoted alone",
  "Avoid duplicate H1s across pages — each page needs its own primary heading",
  "Show expertise with named case studies, not vague 'many clients report' claims",
  "Keep title tags unique across the whole site, not just within a category",
  "Use hreflang correctly if you serve multiple language or regional versions",
  "A well-labeled table of contents helps both readers and jump-link snippets",
  "Update your author page — engines associate content quality with author history",
  "Avoid cloaking — the content a crawler sees must match what users see",
  "Group FAQs by real, distinct questions instead of rephrasing the same one three times",
  "Prioritize Core Web Vitals fixes that affect your highest-traffic templates first",
  "Use numbered lists for sequential processes, bullet lists for unordered facts",
  "A clear pricing or comparison table often becomes the page's most-cited answer",
  "Avoid orphaned redirect chains — point old URLs directly to the final destination",
  "Keep meta descriptions to roughly 155 characters so they don't get cut off",
  "Use specific numbers and dates in headlines — they read as more citable answers",
  "Don't rely on JavaScript alone for critical navigation links",
  "Address the most common objection to your claim directly — it builds trust fast",
  "Keep image file names descriptive; 'blue-running-shoe.jpg' beats 'IMG_0234.jpg'",
  "Use og:title and og:description so shared links look intentional, not broken",
  "Write for the featured-snippet format your query type typically triggers",
  "Avoid duplicate content across staging, www, and non-www versions — pick one canonical",
  "A short video transcript adds crawlable text an embed alone can't provide",
  "Link to your own product pages naturally within genuinely helpful content",
  "Test your site on a throttled mobile connection, not just fast office wifi",
  "Use consistent terminology throughout a page instead of swapping synonyms mid-argument",
  "Include a clear takeaway sentence at the end of each major section",
  "Avoid AI overview cannibalization by making one page the definitive answer, not five",
  "Check Search Console for pages with impressions but zero clicks — the title may be weak",
  "Structured author and organization schema strengthens trust signals sitewide",
  "Keep your sitemap under 50,000 URLs per file; split large sites into multiple sitemaps",
  "Write with the confidence of someone citing a fact, not hedging toward one",
];
