import type { ContentBlock } from "@/lib/data/types";

export type BlockType = ContentBlock["type"];
export type BlockGroup =
  | "Typography" | "Lists" | "Media" | "Quotes" | "Code" | "Tables"
  | "Callouts" | "Interactive" | "Embeds" | "Data & statistics"
  | "Utility" | "Conversion" | "Knowledge" | "Advanced";

export const BLOCK_TYPES: { type: BlockType; group: BlockGroup; label: string }[] = [
  { type: "h2", group: "Typography", label: "Heading 2" },
  { type: "h3", group: "Typography", label: "Heading 3" },
  { type: "h4", group: "Typography", label: "Heading 4" },
  { type: "lead", group: "Typography", label: "Lead paragraph" },
  { type: "p", group: "Typography", label: "Paragraph" },
  { type: "small", group: "Typography", label: "Small text" },
  { type: "caption", group: "Typography", label: "Caption" },
  { type: "ul", group: "Lists", label: "Bullet list" },
  { type: "ol", group: "Lists", label: "Numbered list" },
  { type: "tasklist", group: "Lists", label: "Task list" },
  { type: "figure", group: "Media", label: "Figure" },
  { type: "figures", group: "Media", label: "Side-by-side images" },
  { type: "gallery", group: "Media", label: "Gallery" },
  { type: "video", group: "Media", label: "Video embed" },
  { type: "audio", group: "Media", label: "Audio player" },
  { type: "quote", group: "Quotes", label: "Quote" },
  { type: "pullquote", group: "Quotes", label: "Pull quote" },
  { type: "code", group: "Code", label: "Code block" },
  { type: "table", group: "Tables", label: "Table" },
  { type: "comparisonTable", group: "Tables", label: "Comparison table" },
  { type: "pricing", group: "Tables", label: "Pricing table" },
  { type: "callout", group: "Callouts", label: "Callout" },
  { type: "faq", group: "Interactive", label: "FAQ" },
  { type: "tabs", group: "Interactive", label: "Tabs" },
  { type: "expand", group: "Interactive", label: "Expandable" },
  { type: "socialEmbed", group: "Embeds", label: "Social embed" },
  { type: "map", group: "Embeds", label: "Map" },
  { type: "statCards", group: "Data & statistics", label: "Stat cards" },
  { type: "metricsGrid", group: "Data & statistics", label: "Metrics grid" },
  { type: "progress", group: "Data & statistics", label: "Progress bar" },
  { type: "comparisonCards", group: "Data & statistics", label: "Comparison cards" },
  { type: "divider", group: "Utility", label: "Divider" },
  { type: "spacer", group: "Utility", label: "Spacer" },
  { type: "tags", group: "Utility", label: "Tags" },
  { type: "cta", group: "Conversion", label: "CTA banner" },
  { type: "newsletter", group: "Conversion", label: "Newsletter" },
  { type: "download", group: "Conversion", label: "Download card" },
  { type: "buttonGroup", group: "Conversion", label: "Button group" },
  { type: "takeaways", group: "Knowledge", label: "Key takeaways" },
  { type: "summary", group: "Knowledge", label: "Summary box" },
  { type: "prosCons", group: "Knowledge", label: "Pros & cons" },
  { type: "steps", group: "Knowledge", label: "Step guide" },
  { type: "timeline", group: "Knowledge", label: "Timeline" },
  { type: "references", group: "Knowledge", label: "References" },
  { type: "footnotes", group: "Knowledge", label: "Footnotes" },
  { type: "authorNote", group: "Advanced", label: "Author note" },
  { type: "expertInsight", group: "Advanced", label: "Expert insight" },
  { type: "relatedCard", group: "Advanced", label: "Related card" },
  { type: "resourceList", group: "Advanced", label: "Resource list" },
  { type: "quickFacts", group: "Advanced", label: "Quick facts" },
];
