-- Backfill per-entity SEO copy into existing content rows.
-- Non-destructive: JSONB-merges a "seo" key; skips any row that already has one.
-- Safe to run more than once. Run AFTER deploying the code that reads seo.
-- Tools are static (no DB) and need no backfill.

-- services: 6 rows
update public.services set data = data || '{"seo":{"title":"SEO & Organic Growth Services","description":"Own your category in search and in AI answers with topic clusters, programmatic SEO, and an answer-first content system built to compound for years."}}'::jsonb where slug = 'seo' and not (data ? 'seo');
update public.services set data = data || '{"seo":{"title":"Performance Marketing Services","description":"Profitable paid acquisition at scale — account structure, creative testing systems, and post-click pages engineered to convert, not just to spend."}}'::jsonb where slug = 'performance' and not (data ? 'seo');
update public.services set data = data || '{"seo":{"title":"Content Strategy & Editorial Systems","description":"An editorial engine that demonstrates real thinking: content pillars, a repurposing pipeline, and a QA rubric that turns one idea into a month of distribution."}}'::jsonb where slug = 'content' and not (data ? 'seo');
update public.services set data = data || '{"seo":{"title":"AI Automation & Workflows","description":"Custom AI workflows for research, drafting, analysis, and ops — built with human-in-the-loop QA gates so quality goes up, not down, as output scales."}}'::jsonb where slug = 'ai-workflows' and not (data ? 'seo');
update public.services set data = data || '{"seo":{"title":"Startup Advisory for Founders","description":"Founder-to-founder advisory on growth, distribution, and positioning — hands-on working sessions built for early and growth-stage startups."}}'::jsonb where slug = 'advisory' and not (data ? 'seo');
update public.services set data = data || '{"seo":{"title":"SEO & AI Speaking, Workshops","description":"Keynotes and workshops on SEO, AI workflows, and founder-led growth — built on real experiments and outcomes, not recycled theory or borrowed slides."}}'::jsonb where slug = 'speaking' and not (data ? 'seo');

-- products: 9 rows
update public.products set data = data || '{"seo":{"title":"Book A Sloth Scheduling SaaS","description":"Book A Sloth is an appointment booking and scheduling SaaS that helps businesses manage bookings, collect payments, send reminders, and end scheduling chaos."}}'::jsonb where slug = 'book-a-sloth' and not (data ? 'seo');
update public.products set data = data || '{"seo":{"title":"Ticket Dino Events & Ticketing","description":"Ticket Dino is an event discovery and ticketing platform that helps organizers create, manage, and sell tickets while attendees discover memorable events."}}'::jsonb where slug = 'ticket-dino' and not (data ? 'seo');
update public.products set data = data || '{"seo":{"title":"The Parliament Community Platform","description":"The Parliament is a digital space for meaningful conversations and structured discourse — a hub where communities debate and refine ideas with purpose."}}'::jsonb where slug = 'the-parliament' and not (data ? 'seo');
update public.products set data = data || '{"seo":{"title":"Coffee & Toffee Social Platform","description":"Coffee & Toffee is a social platform built for human connection — friendships, networking, and dating designed around authentic conversation, not noise."}}'::jsonb where slug = 'coffee-and-toffee' and not (data ? 'seo');
update public.products set data = data || '{"seo":{"title":"Link Lantern Creator Link Tool","description":"Link Lantern is a creator-first link-in-bio platform that consolidates your links, content, and digital assets into one destination to boost discoverability."}}'::jsonb where slug = 'link-lantern' and not (data ? 'seo');
update public.products set data = data || '{"seo":{"title":"Alluminaty Alumni Network SaaS","description":"Alluminaty is an alumni networking platform that strengthens lifelong ties between students, graduates, and institutions through mentorship and opportunity."}}'::jsonb where slug = 'alluminaty' and not (data ? 'seo');
update public.products set data = data || '{"seo":{"title":"WhatsLoom Messaging Automation","description":"WhatsLoom automates messaging, nurtures leads, and manages customer conversations through workflows — scaling communication without losing its personal touch."}}'::jsonb where slug = 'whatsloom' and not (data ? 'seo');
update public.products set data = data || '{"seo":{"title":"SERP Sutra SEO Intelligence Tool","description":"SERP Sutra is an SEO intelligence platform giving marketers and businesses the insights they need to improve search visibility, rankings, and organic growth."}}'::jsonb where slug = 'serp-sutra' and not (data ? 'seo');
update public.products set data = data || '{"seo":{"title":"Marketing Bug Growth Community","description":"Marketing Bug is a growth-driven newsletter and community for marketers and founders, sharing tools, insights, and frameworks on modern performance marketing."}}'::jsonb where slug = 'marketing-bug' and not (data ? 'seo');

-- case_studies: 5 rows
update public.case_studies set data = data || '{"seo":{"title":"Local SEO Case Study: Bakery","description":"How a UAE bakery went from invisible in local search to ranking #1 for 40+ searches — and grew online orders 212% with local SEO and Google Business."}}'::jsonb where slug = 'occasion-cakes-local-seo' and not (data ? 'seo');
update public.case_studies set data = data || '{"seo":{"title":"Gaming App Ad Copy Case Study","description":"How a real-money gaming app cut cost per install 34% with a compliant hook library and a disciplined weekly ad-copy testing matrix across Google and Meta."}}'::jsonb where slug = 'khiladi-adda-gaming-ua' and not (data ? 'seo');
update public.case_studies set data = data || '{"seo":{"title":"Franchise Marketing Case Study","description":"How a Maharashtrian vada shop grew from 7 to 19 outlets in 12 months with a franchise microsite, investor narrative, and a full inquiry-to-onboarding funnel."}}'::jsonb where slug = 'dhawade-vadewale-franchise' and not (data ? 'seo');
update public.case_studies set data = data || '{"seo":{"title":"Real Estate Copywriting Case Study","description":"How a plotted-land brand turned commodity plots into life stories, growing qualified site visits 2.6x with narrative ad campaigns and a lead-qualifying funnel."}}'::jsonb where slug = 'stone-and-acres-land-stories' and not (data ? 'seo');
update public.case_studies set data = data || '{"seo":{"title":"Meta Ads Lead-Gen Case Study","description":"How a custom-art D2C brand turned Meta clicks into customers, lifting ROAS to 4.4x with a rebuilt landing page, intent-qualifying forms, and creative testing."}}'::jsonb where slug = 'corart-meta-lead-gen' and not (data ? 'seo');
