// Curated daily-answer words — common, clean 5-letter words.
// APPEND FOREVER: just add to the end. Never reorder or remove existing
// entries once live, or past puzzle numbers would resolve to different words.
//
// Guess validation is lenient in v1 (any 5 a–z letters). To validate guesses
// against a real dictionary later, ship an open list (e.g. dwyl/english-words
// or the standard Wordle "allowed guesses" set) as VALID_GUESSES and check
// membership in lib/games/alfazy.ts -> isValidGuess.

export const ANSWER_LIST: string[] = [
  "about","above","abuse","actor","acute","admit","adopt","adult","after","again",
  "agent","agree","ahead","alarm","album","alert","alike","alive","allow","alone",
  "along","alter","angel","anger","angle","apart","apple","apply","arena","argue",
  "arise","aroma","array","arrow","aside","asset","audio","audit","avoid","awake",
  "award","aware","badly","baker","bases","basic","beach","began","begin","being",
  "below","bench","birth","black","blade","blame","blank","blast","blind","block",
  "blood","board","boast","bonus","boost","booth","bound","brain","brand","brave",
  "bread","break","breed","brick","bride","brief","bring","broad","brown","brush",
  "build","built","bunch","burst","cabin","cable","canal","candy","cargo","carry",
  "carve","catch","cause","chain","chair","chalk","charm","chart","chase","cheap",
  "check","chess","chest","chief","child","chill","china","chose","civil","claim",
  "class","clean","clear","clerk","click","cliff","climb","clock","close","cloth",
  "cloud","coach","coast","could","count","court","cover","crack","craft","crane",
  "crash","cream","crime","cross","crowd","crown","crude","curve","cycle","daily",
  "dairy","dance","dealt","death","debut","delay","depth","doubt","dozen","draft",
  "drama","drank","dream","dress","drill","drink","drive","drove","eager","early",
  "earth","eight","elder","elect","elite","empty","enemy","enjoy","enter","entry",
  "equal","error","event","every","exact","exist","extra","faith","false","fault",
  "favor","feast","fewer","fiber","field","fifth","fifty","fight","final","first",
  "fixed","flame","flash","fleet","float","flood","floor","flour","fluid","focus",
  "force","forth","forty","forum","found","frame","frank","fresh","front","frost",
  "fruit","fully","funny","giant","given","glass","globe","glory","grace","grade",
  "grain","grand","grant","grape","graph","grasp","grass","grave","great","green",
  "greet","grief","group","grown","guard","guess","guest","guide","habit","happy",
  "harsh","heart","heavy","hello","hobby","honey","honor","horse","hotel","house",
  "human","humor","ideal","image","index","inner","input","irony","issue","ivory",
  "japan","jeans","jelly","jewel","joint","judge","juice","known","label","labor",
  "large","laser","later","laugh","layer","learn","lease","least","leave","legal",
  "lemon","level","light","limit","liver","lobby","local","logic","loose","lover",
  "lower","loyal","lucky","lunch","lyric","magic","major","maker","march","match",
  "maybe","mayor","meant","medal","media","metal","meter","might","minor","minus",
  "mixed","model","money","month","moral","motor","mount","mouse","mouth","movie",
  "music","naive","nerve","never","newly","night","noble","noise","north","novel",
  "nurse","ocean","offer","often","onion","order","other","ought","outer","owner",
  "paint","panel","paper","party","pause","peace","pearl","phase","phone","photo",
  "piano","piece","pilot","pitch","place","plain","plane","plant","plate","plaza",
  "point","pound","power","press","price","pride","prime","print","prior","prize",
  "proof","proud","prove","pulse","pupil","queen","query","quest","quick","quiet",
  "quite","radar","radio","raise","rally","range","rapid","reach","react","ready",
  "realm","rebel","refer","relax","reply","rider","ridge","rifle","right","rigid",
  "risky","rival","river","robot","rocky","roman","rough","round","route","royal",
  "rural","sadly","salad","sauce","scale","scare","scene","scope","score","sense",
  "serve","seven","shade","shall","shape","share","sharp","sheep","sheet","shelf",
  "shell","shift","shine","shirt","shock","shore","short","shown","sight","silly",
  "since","siren","sixth","skill","slate","sleep","slice","slide","slope","small",
  "smart","smell","smile","smoke","snake","solar","solid","solve","sorry","sound",
  "south","space","spare","speak","speed","spend","spice","spine","split","spoke",
  "sport","spray","staff","stage","stair","stake","stand","start","state","steam",
  "steel","steep","steer","stern","stick","still","stock","stone","stood","store",
  "storm","story","strip","study","stuff","style","sugar","suite","sunny","super",
  "sweet","swift","swing","sword","table","taken","taste","teach","teeth","tempo",
  "tenth","terms","thank","theft","theme","there","these","thick","thing","think",
  "third","those","three","threw","throw","thumb","tiger","tight","timer","title",
  "toast","today","token","tooth","topic","torch","total","touch","tough","tower",
  "trace","track","trade","trail","train","treat","trend","trial","tribe","trick",
  "troop","truck","truly","trust","truth","twice","twist","ultra","uncle","under",
  "union","unite","unity","until","upper","upset","urban","usage","usual","valid",
  "value","vault","venue","verse","video","virus","visit","vital","vivid","vocal",
  "voice","voter","wagon","waste","watch","water","weary","wheat","wheel","where",
  "which","while","white","whole","whose","widow","width","witch","woman","world",
  "worry","worse","worst","worth","would","wound","wrist","write","wrong","yield",
  "young","youth","zebra",
];
